### ISSUE TITLE
Fetch : Historical Time Series Data

### ISSUE THREAD

**Issue by vijaykakade90** [F4pl0/iex-cloud-java#3]
In historical data api call, you are providing one single price.
How can i fetch whole one day time_series data by minute_by_minute?

**Comment by F4pl0** [comment]
You can use `HistoricalData.historicalEquityPrices` to get data across various timestamps, but unfortunately it seems that the minute-by-minute data is unavailable as of now. It looks like that the smallest data increment is 1 day, even if you set the range to be 1 day, you will still get a single entry for the entry-exit price for that trading day.

Reopen the issue if the API supports smaller data increments, this will be then worked on.

**Comment by vijaykakade90** [comment]
For backtesting, I am looking for minute-by-minute data. But thanks for your quick response on this issue.
